const { Hands } = window;
const { Camera } = window;
const FOCAL = 400;
const MODES = ["dots", "cube", "human", "robot"];
let modeIndex = 0;
const canvas = document.getElementById("screen");
const ctx = canvas.getContext("2d");
const video = document.getElementById("webcam");
const statusEl = document.getElementById("status");
const coordsEl = document.getElementById("coords");
function fitCanvas(){canvas.width=innerWidth;canvas.height=innerHeight;} fitCanvas();
function makeDots(){const g=4,s=30,p=[];for(let z=0;z<g;z++)for(let y=0;y<g;y++)for(let x=0;x<g;x++)p.push({bx:(x-1.5)*s,by:(y-1.5)*s,bz:(z-1.5)*s});return{points:p,edges:[]};}
function makeCube(){const s=60,p=[[-1,-1,-1],[1,-1,-1],[1,1,-1],[-1,1,-1],[-1,-1,1],[1,-1,1],[1,1,1],[-1,1,1]].map(a=>({bx:a[0]*s,by:a[1]*s,bz:a[2]*s}));return{points:p,edges:[[0,1],[1,2],[2,3],[3,0],[4,5],[5,6],[6,7],[7,4],[0,4],[1,5],[2,6],[3,7]]};}
const PUPPET_JOINTS={head:{bx:0,by:-130,bz:0},neck:{bx:0,by:-100,bz:0},lShoulder:{bx:-40,by:-90,bz:0},rShoulder:{bx:40,by:-90,bz:0},lElbow:{bx:-80,by:-50,bz:0},rElbow:{bx:80,by:-50,bz:0},lWrist:{bx:-110,by:-10,bz:0},rWrist:{bx:110,by:-10,bz:0},lFinger:{bx:-130,by:10,bz:0},rFinger:{bx:130,by:10,bz:0},chest:{bx:0,by:-60,bz:0},hip:{bx:0,by:20,bz:0},lHip:{bx:-25,by:20,bz:0},rHip:{bx:25,by:20,bz:0},lKnee:{bx:-30,by:80,bz:0},rKnee:{bx:30,by:80,bz:0},lAnkle:{bx:-35,by:140,bz:0},rAnkle:{bx:35,by:140,bz:0}};
const JOINT_NAMES=Object.keys(PUPPET_JOINTS);
const PUPPET_BONES=[["head","neck"],["neck","lShoulder"],["neck","rShoulder"],["lShoulder","lElbow"],["rShoulder","rElbow"],["lElbow","lWrist"],["rElbow","rWrist"],["lWrist","lFinger"],["rWrist","rFinger"],["neck","chest"],["chest","hip"],["hip","lHip"],["hip","rHip"],["lHip","lKnee"],["rHip","rKnee"],["lKnee","lAnkle"],["rKnee","rAnkle"]];
const puppet=Object.fromEntries(JOINT_NAMES.map(n=>[n,{x:PUPPET_JOINTS[n].bx,y:PUPPET_JOINTS[n].by,z:0,vx:0,vy:0}]));
const JOINT_REST=Object.fromEntries(JOINT_NAMES.map(n=>[n,{...PUPPET_JOINTS[n]}]));
const rodTarget={body:{x:0,y:0},head:{x:0,y:0},lHand:{x:0,y:0},rHand:{x:0,y:0}};
function makeHuman(){return{points:JOINT_NAMES.map(n=>({...PUPPET_JOINTS[n]})),edges:PUPPET_BONES.map(([a,b])=>[JOINT_NAMES.indexOf(a),JOINT_NAMES.indexOf(b)])};}
let shapes={dots:makeDots(),cube:makeCube(),human:makeHuman()};
async function loadShapes(){for(const name of ["dots","cube","human","robot"]){try{const r=await fetch(`shapes/${name}.json`,{cache:"no-store"});if(!r.ok)throw Error(`${name}.json ${r.status}`);const s=await r.json();if(s.joints){const names=s.joints.map(j=>j.id),ix=Object.fromEntries(names.map((n,i)=>[n,i]));shapes[name]={points:s.joints.map(j=>({bx:j.x,by:j.y,bz:j.z||0})),edges:(s.bones||[]).map(([a,b])=>[ix[a],ix[b]]).filter(e=>e[0]!==undefined&&e[1]!==undefined)};}else if(s.grid){const p=[],g=s.grid,sc=g.scale||30;for(let z=0;z<g.z;z++)for(let y=0;y<g.y;y++)for(let x=0;x<g.x;x++)p.push({bx:(x-(g.x-1)/2)*sc,by:(y-(g.y-1)/2)*sc,bz:(z-(g.z-1)/2)*sc});shapes[name]={points:p,edges:[]};}}catch(e){console.warn("shape load failed",name,e);}}}
let handX=0,handY=0,handPinch=1,handX_raw=0,handY_raw=0,headTipX=.5,headTipY=.5,lThumbX=.5,lThumbY=.5,rIndexX=.5,rIndexY=.5,smoothX=0,smoothY=0,smoothPinch=1,rainbowMode=false,hue=0,clapFlash=0;
function updatePuppet(){const B=40;rodTarget.body.x=handX*B;rodTarget.body.y=handY*B*.5;rodTarget.head.x=(headTipX-handX_raw)*B*2;rodTarget.head.y=(headTipY-handY_raw)*B*2;rodTarget.lHand.x=(lThumbX-.5)*-B*3;rodTarget.lHand.y=(lThumbY-.5)*-B*3;rodTarget.rHand.x=(rIndexX-.5)*-B*3;rodTarget.rHand.y=(rIndexY-.5)*-B*3;for(const n of JOINT_NAMES){const r=JOINT_REST[n],p=puppet[n];let tx=r.bx,ty=r.by;if(n==="head"||n==="neck"){tx+=rodTarget.body.x*.6+rodTarget.head.x*.4;ty+=rodTarget.body.y*.4+rodTarget.head.y*.6;}else if(n==="chest"||n==="hip"){tx+=rodTarget.body.x;ty+=rodTarget.body.y;}else if(n.startsWith("l")&&/(Shoulder|Elbow|Wrist|Finger)/.test(n)){const t=n.includes("Finger")?1:n.includes("Wrist")?.9:n.includes("Elbow")?.5:.2;tx+=rodTarget.body.x*(1-t)+rodTarget.lHand.x*t;ty+=rodTarget.body.y*(1-t)+rodTarget.lHand.y*t;}else if(n.startsWith("r")&&/(Shoulder|Elbow|Wrist|Finger)/.test(n)){const t=n.includes("Finger")?1:n.includes("Wrist")?.9:n.includes("Elbow")?.5:.2;tx+=rodTarget.body.x*(1-t)+rodTarget.rHand.x*t;ty+=rodTarget.body.y*(1-t)+rodTarget.rHand.y*t;}const dx=tx-p.x,dy=ty-p.y;p.vx=(p.vx+dx*.12)*.7;p.vy=(p.vy+dy*.12+.3)*.7;p.x+=p.vx;p.y+=p.vy;}}
function rotate(p,ax,ay){let{x,y,z}=p,cx=Math.cos(ax),sx=Math.sin(ax),cy=Math.cos(ay),sy=Math.sin(ay),ty=y*cx-z*sx,tz=y*sx+z*cx; y=ty;z=tz;const tx=x*cy+z*sy;z=-x*sy+z*cy;x=tx;p.x=x;p.y=y;p.z=z;}
function color(i,d,a){return rainbowMode?`hsla(${(hue+i*8)%360},90%,${50+d*30}%,${a})`:`rgba(51,255,51,${a})`;}
function onResults(r){if(!r.multiHandLandmarks?.length){statusEl.textContent="no hand detected";return;}const lm=r.multiHandLandmarks[0];handX_raw=(lm[0].x-.5)*-2;handY_raw=(lm[0].y-.5)*-2;handX=handX_raw;handY=handY_raw;handPinch=Math.hypot(lm[8].x-lm[4].x,lm[8].y-lm[4].y);headTipX=lm[8].x;headTipY=lm[8].y;lThumbX=lm[4].x;lThumbY=lm[4].y;rIndexX=lm[8].x;rIndexY=lm[8].y;statusEl.textContent=`hand ✓ | mode: ${MODES[modeIndex]}`;coordsEl.textContent=`x:${handX.toFixed(2)} y:${handY.toFixed(2)} pinch:${handPinch.toFixed(2)}`;}
function render(){const mode=MODES[modeIndex];ctx.fillStyle=rainbowMode?"rgba(5,5,15,.3)":"rgba(10,10,10,.25)";ctx.fillRect(0,0,canvas.width,canvas.height);smoothX+=(handX-smoothX)*.08;smoothY+=(handY-smoothY)*.08;smoothPinch+=(handPinch-smoothPinch)*.06;const ax=smoothY*Math.PI,ay=smoothX*Math.PI,zoom=mode==="human"||mode==="robot"?1:.5+smoothPinch*2;if(mode==="human")updatePuppet();hue=(hue+.5)%360;const shape=shapes[mode];if(shape){const q=shape.points.map((p,i)=>{let v;if(mode==="human"){const n=JOINT_NAMES[i],pp=puppet[n];v={x:pp.x,y:pp.y,z:pp.z};}else v={x:p.bx*zoom,y:p.by*zoom,z:p.bz*zoom};rotate(v,ax,ay);return v;});for(const [a,b] of shape.edges){const A=q[a],B=q[b];if(!A||!B||A.z<=-FOCAL+2||B.z<=-FOCAL+2)continue;const da=FOCAL/(A.z+FOCAL),db=FOCAL/(B.z+FOCAL);ctx.strokeStyle=color(a,(da+db)/2,.8);ctx.lineWidth=mode==="human"||mode==="robot"?3:2;ctx.beginPath();ctx.moveTo(canvas.width/2+A.x*da,canvas.height/2+A.y*da);ctx.lineTo(canvas.width/2+B.x*db,canvas.height/2+B.y*db);ctx.stroke();}for(let i=0;i<q.length;i++){const v=q[i];if(v.z<=-FOCAL+2)continue;const d=FOCAL/(v.z+FOCAL);ctx.fillStyle=color(i,d,.9);ctx.beginPath();ctx.arc(canvas.width/2+v.x*d,canvas.height/2+v.y*d,(mode==="human"||mode==="robot"?(i===0?14:6):4)*d,0,Math.PI*2);ctx.fill();}}requestAnimationFrame(render);}
function setMode(name){const i=MODES.indexOf(name);if(i<0)return;modeIndex=i;document.querySelectorAll(".mode-btn").forEach(b=>b.classList.toggle("active",b.dataset.mode===name));}
async function init(){try{await loadShapes();const stream=await navigator.mediaDevices.getUserMedia({video:{width:640,height:480,facingMode:"user"}});video.srcObject=stream;const hands=new Hands({locateFile:f=>`https://cdn.jsdelivr.net/npm/@mediapipe/hands/${f}`});hands.setOptions({maxNumHands:1,modelComplexity:1,minDetectionConfidence:.7,minTrackingConfidence:.5});hands.onResults(onResults);const camera=new Camera(video,{onFrame:async()=>await hands.send({image:video}),width:640,height:480});await camera.start();document.querySelectorAll(".mode-btn").forEach(b=>b.addEventListener("click",()=>setMode(b.dataset.mode)));document.getElementById("rainbow-btn").addEventListener("click",()=>{rainbowMode=!rainbowMode;document.getElementById("rainbow-btn").classList.toggle("on",rainbowMode);});document.addEventListener("shadowshapechange",e=>setMode(e.detail.shape));document.addEventListener("keydown",e=>{if(e.key.toLowerCase()==="f")setMode(MODES[(modeIndex+1)%MODES.length]);});statusEl.textContent="camera ready / JSON shapes loaded";render();}catch(e){statusEl.textContent=`error: ${e.message}`;console.error(e);}}
window.addEventListener("resize",fitCanvas);init();
